### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by oshimayoan** [mikaelmello/wallet-automate#3]
Hey @mikaelmello, great work on this wallet automation! Sorry for opening an issue even though its not an issue as I don't know how to reach you out.

As I'm also user of wallet app, I'm curious about what is this automaton of yours does and how it works as I'm thinking of automating mine as well. It would be really helpful if you can give me more explanation on that or maybe some screenshots or recording of the action.

I'd love to hear more from you.
I really appreciate any help you can provide.

**Comment by mikaelmello** [comment]
Hey @oshimayoan, this is a project that didn't go anywhere if I recall correctly.

I had stopped using Wallet so I kind of abandoned it. I even forgot this repo existed, will likely archive it

**Comment by oshimayoan** [comment]
Ah, I see. I thought you had succeeded on this one and curious about your approach.

Alright, thanks for the response @mikaelmello
